<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ICPL11544" name="domestictest.Excel_loap" tests="1" failures="1" timestamp="3 Apr 2017 09:13:31 GMT" time="0.000" errors="0">
  <testcase name="scenario5" time="0.000" classname="domestictest.Excel_loap">
    <failure type="java.lang.RuntimeException" message="com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data.xlsx">
      <![CDATA[java.lang.RuntimeException: com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data.xlsx
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:161)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:429)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:741)
	at org.testng.TestRunner.run(TestRunner.java:595)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
Caused by: com.qmetry.qaf.automation.testng.DataProviderException: Error while fetching data from resources/data.xlsx
	at com.qmetry.qaf.automation.util.CSVUtil.getCSVDataAsMap(CSVUtil.java:186)
	at com.qmetry.qaf.automation.testng.pro.DataProviderUtil.getCSVData(DataProviderUtil.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:135)
	... 20 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 31
	at java.lang.String.charAt(Unknown Source)
	at com.qmetry.qaf.automation.util.StringUtil.parseCSV(StringUtil.java:295)
	at com.qmetry.qaf.automation.util.CSVUtil.getCSVDataAsMap(CSVUtil.java:163)
	... 27 more
]]>
    </failure>
  </testcase> <!-- scenario5 -->
</testsuite> <!-- domestictest.Excel_loap -->
